/**
 * generated by Xtext 2.14.0
 */
package com.acme.homeautomation.dsl.web;

import com.acme.homeautomation.dsl.web.AbstractHarDslWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class HarDslWebModule extends AbstractHarDslWebModule {
}
