/**
 * generated by Xtext 2.14.0
 */
package com.acme.homeautomation.dsl.scoping;

import com.acme.homeautomation.dsl.scoping.AbstractHarDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class HarDslScopeProvider extends AbstractHarDslScopeProvider {
}
