/**
 * generated by Xtext 2.14.0
 */
package com.acme.homeautomation.dsl.ui;

import com.acme.homeautomation.dsl.ui.AbstractHarDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class HarDslUiModule extends AbstractHarDslUiModule {
  public HarDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
