/*
 * generated by Xtext 2.14.0
 */
package com.acme.homeautomation.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractHarDslScopeProvider extends DelegatingScopeProvider {
}
