/**
 * generated by Xtext 2.14.0
 */
package com.acme.homeautomation.dsl.validation;

import com.acme.homeautomation.dsl.ModelAccess;
import com.acme.homeautomation.dsl.harDsl.HarDslPackage;
import com.acme.homeautomation.dsl.harDsl.Rule;
import com.acme.homeautomation.dsl.validation.AbstractHarDslValidator;
import java.util.Objects;
import org.eclipse.xtext.validation.Check;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class HarDslValidator extends AbstractHarDslValidator {
  @Check
  public void checkConditionAndActionFromDifferentDevices(final Rule rule) {
    boolean _equals = Objects.equals(ModelAccess.declaringDevice(rule.getWhen()), 
      ModelAccess.declaringDevice(rule.getThen()));
    if (_equals) {
      this.warning("Condition (when) and action (then) should refer to different devices.", 
        HarDslPackage.Literals.RULE__WHEN);
    }
  }
}
