/*
 * generated by Xtext 2.14.0
 */
package com.acme.homeautomation.dsl.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link HarDslWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractHarDslWebModule extends DefaultWebModule {

}
