/**
 * generated by Xtext 2.14.0
 */
package com.acme.homeautomation.dsl;

import com.acme.homeautomation.dsl.HarDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class HarDslStandaloneSetup extends HarDslStandaloneSetupGenerated {
  public static void doSetup() {
    new HarDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
