/**
 * generated by Xtext 2.14.0
 */
package com.acme.homeautomation.dsl;

import com.acme.homeautomation.dsl.AbstractHarDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class HarDslRuntimeModule extends AbstractHarDslRuntimeModule {
}
