/*
 * generated by Xtext 2.14.0
 */
package com.acme.homeautomation.dsl.ui.tests;

import com.acme.homeautomation.dsl.ui.internal.DslActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class HarDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("com.acme.homeautomation.dsl.HarDsl");
	}

}
