/**
 * generated by Xtext 2.14.0
 */
package com.acme.homeautomation.dsl.ide;

import com.acme.homeautomation.dsl.ide.AbstractHarDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class HarDslIdeModule extends AbstractHarDslIdeModule {
}
