/**
 * generated by Xtext 2.14.0
 */
package com.acme.homeautomation.dsl.ui.contentassist;

import com.acme.homeautomation.dsl.ui.contentassist.AbstractHarDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class HarDslProposalProvider extends AbstractHarDslProposalProvider {
}
