/*
 * generated by Xtext 2.14.0
 */
package com.acme.homeautomation.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class HarDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/acme/homeautomation/dsl/parser/antlr/internal/InternalHarDsl.tokens");
	}
}
