/*
 * generated by Xtext 2.14.0
 */
package com.acme.homeautomation.dsl.parser.antlr;

import com.acme.homeautomation.dsl.parser.antlr.internal.InternalHarDslParser;
import com.acme.homeautomation.dsl.services.HarDslGrammarAccess;
import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class HarDslParser extends AbstractAntlrParser {

	@Inject
	private HarDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalHarDslParser createParser(XtextTokenStream stream) {
		return new InternalHarDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public HarDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(HarDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
