/*
 * generated by Xtext 2.14.0
 */
package com.acme.homeautomation.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class HarDslRuntimeModule extends AbstractHarDslRuntimeModule {
}
