/*
 * generated by Xtext 2.14.0
 */
package com.acme.homeautomation.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class HarDslStandaloneSetup extends HarDslStandaloneSetupGenerated {

	def static void doSetup() {
		new HarDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
